//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.BlogsTags = new HashSet<BlogsTags>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public int AuthorID { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UniqueURL { get; set; }
        public string ImagePath { get; set; }
        public string ImageThumbnailPath { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogsTags> BlogsTags { get; set; }
    }
}
