USE [SparkServer]
GO

CREATE TABLE [BlogTag] (
	
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),

	[Name] VARCHAR(100) NOT NULL,

	[Active] BIT NOT NULL DEFAULT 1,

	[CreateDate] DATETIME NOT NULL DEFAULT GETDATE()
)