USE [SparkServer]
GO

CREATE TABLE [BlogsTags] (
	
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),

	[BlogID] INT NOT NULL,
	CONSTRAINT [FK_BlogTag_Blog] FOREIGN KEY ([BlogID]) REFERENCES [Blog]([ID]),
	
	[TagID] INT NOT NULL,
	CONSTRAINT [FK_BlogTag_Tag] FOREIGN KEY ([TagID]) REFERENCES [BlogTag]([ID]),

	[Active] BIT NOT NULL DEFAULT 1,

	[CreateDate] DATETIME NOT NULL DEFAULT GETDATE()

)