USE [SparkServer]
GO

CREATE TABLE [Video] (
	
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),

	[Title] VARCHAR(500) NOT NULL,

	[Subtitle] VARCHAR(500) NULL,

	[VideoURL] VARCHAR(500) NOT NULL,

	[ImageThumbnailPath] VARCHAR(1000) NULL,

	[PublishDate] DATETIME NULL,

	[AuthorID] INT NOT NULL,
	CONSTRAINT [FK_Video_Author] FOREIGN KEY ([AuthorID]) REFERENCES [Author]([ID]),

	[Active] BIT NOT NULL DEFAULT 1,

	[CreateDate] DATETIME NOT NULL DEFAULT GETDATE()

)